/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IngredientBlock: typeof import('./components/ingredient/ingredientBlock.vue')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCollapseItem: typeof import('naive-ui')['NCollapseItem']
    README: typeof import('./components/README.md')['default']
    RecipeBlock: typeof import('./components/recipe/recipeBlock.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StockBlock: typeof import('./components/stock/stockBlock.vue')['default']
    TheCounter: typeof import('./components/TheCounter.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    TheInput: typeof import('./components/TheInput.vue')['default']
  }
}
